/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import java.awt.Font;

/**
 *
 * @author Joice
 */

public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        
        lblFrase.setText("<html>Estou pensando em um valor entre 1 e 5. advinhe!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGenio = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        lblescolha = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        spnNumero = new javax.swing.JSpinner();
        lblFrase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genioooooo (1).png"))); // NOI18N
        jPanel1.add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balao-de-fala-transparente2 (1).png"))); // NOI18N
        jPanel1.add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 230, 200));

        lblescolha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblescolha.setText("ESCOLHA UM NÚMERO");
        jPanel1.add(lblescolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 80, -1));

        spnNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jPanel1.add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 40, -1));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFrase.setText("FRASE"); // NOI18N
        jPanel1.add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        
                double n = 1 + Math.random() * 5;
        
        // sorteia o numero 
        int valor = (int) n;
        
        // valor sorteado
        int num = Integer.parseInt(spnNumero.getValue().toString());
        
        // Valor sorteado
        String f1 = "<html>ACERTOU! </html>";
        String f2 = "<html>ERROU! Eu pensei em " + valor + "</html>";
        
        String res = (valor == num)?f1:f2; 
        //variaveis res
        
       lblFrase.setFont(new Font("Arial Black", Font.PLAIN,15));
       lblFrase.setText(res);
        
        
        System.out.println(n);      
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblescolha;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
