/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class CursoEditar extends javax.swing.JFrame {

    private Curso cursoParaEdicao; 
                                 
    @Autowired
    private CursoIController cursoController;

    public CursoEditar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void setCurso(Curso curso) {
        
        this.cursoParaEdicao = curso; // Atribui o curso recebido a variável de instância
        
        // Preenche os campos da tela com os dados do curso
        if (cursoParaEdicao != null) {
            txtNome.setText(cursoParaEdicao.getNome());
            txtCodigo.setText(cursoParaEdicao.getCodigoCurso());
            txtCoordenador.setText(cursoParaEdicao.getCoordenador());
            
            if (cursoParaEdicao.isAtivo()) { 
                cbbDisponibilidade.setSelectedItem("Ativo");
            } else {
                cbbDisponibilidade.setSelectedItem("Inativo");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblCoordenador = new javax.swing.JLabel();
        txtCoordenador = new javax.swing.JTextField();
        lblDisponbilidade = new javax.swing.JLabel();
        cbbDisponibilidade = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 205, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("EDITAR DADOS DO CURSO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 22, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 51, 51));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 46, 50, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 46, 310, 30));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 86, 310, 30));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 51, 51));
        lblCodigo.setText("Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 86, 50, -1));

        lblCoordenador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCoordenador.setForeground(new java.awt.Color(0, 51, 51));
        lblCoordenador.setText("Coordenador");
        jPanel1.add(lblCoordenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 126, 100, -1));
        jPanel1.add(txtCoordenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 126, 310, 30));

        lblDisponbilidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDisponbilidade.setForeground(new java.awt.Color(0, 51, 51));
        lblDisponbilidade.setText("Disponibilidade");
        jPanel1.add(lblDisponbilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 166, 110, -1));

        cbbDisponibilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jPanel1.add(cbbDisponibilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 166, 310, 30));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 176, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         if (cursoParaEdicao != null) {
            // Atualiza o objeto cursoParaEdicao com os dados da tela
            cursoParaEdicao.setNome(txtNome.getText());
            cursoParaEdicao.setCodigoCurso(txtCodigo.getText());
            cursoParaEdicao.setCoordenador(txtCoordenador.getText());
            
            String selectedAvailability = (String) cbbDisponibilidade.getSelectedItem();
            cursoParaEdicao.setAtivo("Ativo".equals(selectedAvailability)); // Define true se "Ativo", false se "Inativo"

            try {
                // Chama o método de atualização no controller
                cursoController.update(cursoParaEdicao); 
                JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar curso: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum curso selecionado para edição.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbDisponibilidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCoordenador;
    private javax.swing.JLabel lblDisponbilidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCoordenador;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
