/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class CursoCadastro extends javax.swing.JFrame {

    @Autowired
    private CursoIController cursoController;

    public CursoCadastro() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cbbDisponibilidade.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCoordenador = new javax.swing.JLabel();
        lblDisponbilidade = new javax.swing.JLabel();
        txtCoordenador = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        cbbDisponibilidade = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 205, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 51, 51));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 50, 20));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 51, 51));
        lblCodigo.setText("Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, 20));

        lblCoordenador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCoordenador.setForeground(new java.awt.Color(0, 51, 51));
        lblCoordenador.setText("Coordenador");
        jPanel1.add(lblCoordenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 20));

        lblDisponbilidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDisponbilidade.setForeground(new java.awt.Color(0, 51, 51));
        lblDisponbilidade.setText("Disponibilidade");
        jPanel1.add(lblDisponbilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 20));
        jPanel1.add(txtCoordenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 310, 30));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 310, 30));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 310, 30));

        cbbDisponibilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jPanel1.add(cbbDisponibilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 310, 30));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 51, 51));
        lblDescricao.setText("GERENCIAMENTO DE CURSOS");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Cria uma nova instância de Curso
        Curso novoCurso = new Curso();

        //Coleta os dados da tela e seta no objeto Curso
        novoCurso.setNome(txtNome.getText());
        novoCurso.setCodigoCurso(txtCodigo.getText());
        novoCurso.setCoordenador(txtCoordenador.getText());

        //item selecionado no JComboBox
        String selectedAvailability = (String) cbbDisponibilidade.getSelectedItem();
        novoCurso.setAtivo("Ativo".equals(selectedAvailability)); // True se "Ativo", False se "Inativo"

        try {
            //Chama o método save do controller
            cursoController.save(novoCurso); 
            JOptionPane.showMessageDialog(this, "Curso cadastrado com sucesso!"); // Mensagem genérica de sucesso
            
            //Limpa os campos após o cadastro bem-sucedido
            limparCampos();
        } catch (IllegalArgumentException e) {
            // Captura exceções de validação específicas (IllegalArgumentException)
            JOptionPane.showMessageDialog(this, "Erro de Validação: " + e.getMessage(), "Erro no Cadastro", JOptionPane.WARNING_MESSAGE);
        } catch (RuntimeException e) {
            // Captura a RuntimeException genérica ou outras RuntimeExceptions que podem vir do service/DAO.
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar curso: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Captura qualquer outra exceção inesperada
            JOptionPane.showMessageDialog(this, "Um erro inesperado ocorreu: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
        // Limpa todos os campos do formulario
        private void limparCampos() {
            txtNome.setText("");
            txtCodigo.setText("");
            txtCoordenador.setText("");
            cbbDisponibilidade.setSelectedIndex(0); // Seleciona o primeiro item do combobox
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbDisponibilidade;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCoordenador;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDisponbilidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCoordenador;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
